name: test

on:
  push:

jobs:
  migrate:
    name: tst
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get specific changed files
        uses: tj-actions/changed-files@v13
        with:
          files: |
            dir/inside_dir/**
            dir/file.txt

      - name: Check
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "One or more files listed above has changed."