name: test

on:
  push:

jobs:
  migrate:
    name: tst
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v14.1
        with:
          files: |
            dir/inside_dir/**
            **/dir/file.txt
            file.txt

      - name: No If
        run: |
          echo ${{ steps.changed-files-specific.outputs.any_changed }}
          echo ${{ steps.changed-files.outputs.any_changed }}
          echo ${{ steps.changed-files.outputs.modified_files }}
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Check
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "One or more files listed above has changed."